const express = require('express')
const app = express()
const cors = require('cors')
require('./model/db')
app.use(express.json())
app.use(cors())
const userRoute = require('./route/userRoute')
const categoryRoute = require('./route/categoryRoute')
const transactionRoute = require('./route/transactionRoute')
app.use('/auth',userRoute)
app.use('/category',categoryRoute)
app.use('/transaction',transactionRoute)
app.get('/',(req,res)=>{
    res.json({error:false})
})
app.listen(5000,()=>console.log('server running at port 5000'))